/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MissionPlannerRouteImport } from './routes/mission-planner'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as WorkRouteImport } from './routes/work'
import { Route as CapabilitiesIndexRouteImport } from './routes/capabilities.index'
import { Route as CapabilitiesSlugRouteImport } from './routes/capabilities.$slug'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionPlannerRoute = MissionPlannerRouteImport.update({
  id: '/mission-planner',
  path: '/mission-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesIndexRoute = CapabilitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CapabilitiesRoute,
} as any)
const CapabilitiesSlugRoute = CapabilitiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CapabilitiesRoute,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/capabilities': typeof CapabilitiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/mission-planner': typeof MissionPlannerRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/work': typeof WorkRouteWithChildren
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/capabilities/': typeof CapabilitiesIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/mission-planner': typeof MissionPlannerRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/capabilities': typeof CapabilitiesIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/capabilities': typeof CapabilitiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/mission-planner': typeof MissionPlannerRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/work': typeof WorkRouteWithChildren
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/capabilities/': typeof CapabilitiesIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/capabilities'
    | '/contact'
    | '/mission-planner'
    | '/privacy'
    | '/terms'
    | '/trust'
    | '/work'
    | '/capabilities/$slug'
    | '/work/$slug'
    | '/capabilities/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/mission-planner'
    | '/privacy'
    | '/terms'
    | '/trust'
    | '/capabilities/$slug'
    | '/work/$slug'
    | '/capabilities'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/capabilities'
    | '/contact'
    | '/mission-planner'
    | '/privacy'
    | '/terms'
    | '/trust'
    | '/work'
    | '/capabilities/$slug'
    | '/work/$slug'
    | '/capabilities/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  CapabilitiesRoute: typeof CapabilitiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  MissionPlannerRoute: typeof MissionPlannerRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-planner': {
      id: '/mission-planner'
      path: '/mission-planner'
      fullPath: '/mission-planner'
      preLoaderRoute: typeof MissionPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities/': {
      id: '/capabilities/'
      path: '/'
      fullPath: '/capabilities/'
      preLoaderRoute: typeof CapabilitiesIndexRouteImport
      parentRoute: typeof CapabilitiesRoute
    }
    '/capabilities/$slug': {
      id: '/capabilities/$slug'
      path: '/$slug'
      fullPath: '/capabilities/$slug'
      preLoaderRoute: typeof CapabilitiesSlugRouteImport
      parentRoute: typeof CapabilitiesRoute
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof WorkRoute
    }
  }
}

interface CapabilitiesRouteChildren {
  CapabilitiesSlugRoute: typeof CapabilitiesSlugRoute
  CapabilitiesIndexRoute: typeof CapabilitiesIndexRoute
}

const CapabilitiesRouteChildren: CapabilitiesRouteChildren = {
  CapabilitiesSlugRoute: CapabilitiesSlugRoute,
  CapabilitiesIndexRoute: CapabilitiesIndexRoute,
}

const CapabilitiesRouteWithChildren = CapabilitiesRoute._addFileChildren(
  CapabilitiesRouteChildren,
)

interface WorkRouteChildren {
  WorkSlugRoute: typeof WorkSlugRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkSlugRoute: WorkSlugRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  CapabilitiesRoute: CapabilitiesRouteWithChildren,
  ContactRoute: ContactRoute,
  MissionPlannerRoute: MissionPlannerRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
